#! /bin/bash
sudo apt update
sudo apt --yes install zsh
git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
if [  -f ~/.zshrc ]; then
    echo "###############
    old .zshrc file found:
    moving the old one to .zshrc_backup"
    mv ~/.zshrc ~/.zshrc_backup
fi
sudo chsh -s /bin/zsh $USER
export ZSH_CUSTOM="/home/$USER/.oh-my-zsh/custom"
git clone https://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_CUSTOM/plugins/zsh-syntax-highlighting
cp -f .zshrc ~/.zshrc
echo "#################

You now need to exit this shell, next logging will be under zsh shell"
